<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.openntf.example</groupId>
		<artifactId>webinar-todo-examples</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>jnosql-driver-keep</artifactId>

	<name>Jakarta NoSQL Driver For Domino Via Keep</name>

	<url>https://github.com/OpenNTF/jnosql-driver-proton</url>
	<inceptionYear>2025</inceptionYear>

	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>
	
	<distributionManagement>
		<repository>
			<id>artifactory.openntf.org</id>
			<name>artifactory.openntf.org</name>
			<url>https://artifactory.openntf.org/openntf</url>
		</repository>
	</distributionManagement>
	
	<dependencies>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<version>3.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.json.bind</groupId>
			<artifactId>jakarta.json.bind-api</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.json</groupId>
			<artifactId>jakarta.json-api</artifactId>
			<version>2.1.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<version>3.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.ws.rs</groupId>
			<artifactId>jakarta.ws.rs-api</artifactId>
			<version>3.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.microprofile.rest.client</groupId>
			<artifactId>microprofile-rest-client-api</artifactId>
			<version>3.0</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>org.openntf.xsp</groupId>
			<artifactId>org.openntf.xsp.jakarta.nosql.driver</artifactId>
			<version>3.5.0-SNAPSHOT</version>
			<exclusions>
        <exclusion>
          <groupId>org.openntf.xsp</groupId>
          <artifactId>org.openntf.xsp.jakartaee.osgiresourcelocator</artifactId>
        </exclusion>
      </exclusions>
		</dependency>
		<dependency>
			<groupId>jakarta.data</groupId>
			<artifactId>jakarta.data-api</artifactId>
			<version>1.0.1</version>
		</dependency>
		<dependency>
			<groupId>jakarta.nosql</groupId>
			<artifactId>jakarta.nosql-api</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jnosql.communication</groupId>
			<artifactId>jnosql-communication-query</artifactId>
			<version>${jnosql-version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jnosql.mapping</groupId>
			<artifactId>jnosql-mapping-reflection</artifactId>
			<version>${jnosql-version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jnosql.mapping</groupId>
			<artifactId>jnosql-mapping-document</artifactId>
			<version>${jnosql-version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jnosql.mapping</groupId>
			<artifactId>jnosql-mapping-validation</artifactId>
			<version>${jnosql-version}</version>
		</dependency>
	</dependencies>
</project>