/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Runs an existing agent in a given database using a specific document as the agent's run context.
 * The is the status message of the response.
 **/

public class AgentPayload {

  /**
   * The agentName in the given database.
   **/
  @JsonbProperty("agentName")
  private String agentName;

  /**
   * Additional content to pass to the agent
   **/
  @JsonbProperty("payload")
  private Object payload;

  /**
   * The agentName in the given database.
   * 
   * @return agentName
   **/
  public String getAgentName() {
    return agentName;
  }

  /**
   * Set agentName
   **/
  public void setAgentName(String agentName) {
    this.agentName = agentName;
  }

  public AgentPayload agentName(String agentName) {
    this.agentName = agentName;
    return this;
  }

  /**
   * Additional content to pass to the agent
   * 
   * @return payload
   **/
  public Object getPayload() {
    return payload;
  }

  /**
   * Set payload
   **/
  public void setPayload(Object payload) {
    this.payload = payload;
  }

  public AgentPayload payload(Object payload) {
    this.payload = payload;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentPayload {\n");

    sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

