/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;
import jakarta.validation.constraints.NotNull;

/**
 * payload for /run/agent endpoints
 **/

public class AgentPayloadAsync {

  /**
   * The name of the agent.
   **/
  @JsonbProperty("agentName")
  private String agentName;

  /**
   * URL to call, only used if async=true
   **/
  @JsonbProperty("callbackUrl")
  private String callbackUrl;

  /**
   * Http request method you want to use when sending the callbackurl.
   **/
  @JsonbProperty("method")
  private String method;

  /**
   * URL to call if agent responds with status code other than 200. Only used if async=true
   **/
  @JsonbProperty("callbackUrlError")
  private String callbackUrlError;

  /**
   * Additional content to pass to the agent
   **/
  @JsonbProperty("payload")
  private Object payload;

  /**
   * Whether the agent should run as current user or as server. If the agent is designed to only run
   * as the current web user, this property cannot be set to true.
   **/
  @JsonbProperty("runAsServer")
  private Boolean runAsServer;

  /**
   * The name of the agent.
   * 
   * @return agentName
   **/
  @NotNull
  public String getAgentName() {
    return agentName;
  }

  /**
   * Set agentName
   **/
  public void setAgentName(String agentName) {
    this.agentName = agentName;
  }

  public AgentPayloadAsync agentName(String agentName) {
    this.agentName = agentName;
    return this;
  }

  /**
   * URL to call, only used if async&#x3D;true
   * 
   * @return callbackUrl
   **/
  public String getCallbackUrl() {
    return callbackUrl;
  }

  /**
   * Set callbackUrl
   **/
  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public AgentPayloadAsync callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * Http request method you want to use when sending the callbackurl.
   * 
   * @return method
   **/
  public String getMethod() {
    return method;
  }

  /**
   * Set method
   **/
  public void setMethod(String method) {
    this.method = method;
  }

  public AgentPayloadAsync method(String method) {
    this.method = method;
    return this;
  }

  /**
   * URL to call if agent responds with status code other than 200. Only used if async&#x3D;true
   * 
   * @return callbackUrlError
   **/
  public String getCallbackUrlError() {
    return callbackUrlError;
  }

  /**
   * Set callbackUrlError
   **/
  public void setCallbackUrlError(String callbackUrlError) {
    this.callbackUrlError = callbackUrlError;
  }

  public AgentPayloadAsync callbackUrlError(String callbackUrlError) {
    this.callbackUrlError = callbackUrlError;
    return this;
  }

  /**
   * Additional content to pass to the agent
   * 
   * @return payload
   **/
  public Object getPayload() {
    return payload;
  }

  /**
   * Set payload
   **/
  public void setPayload(Object payload) {
    this.payload = payload;
  }

  public AgentPayloadAsync payload(Object payload) {
    this.payload = payload;
    return this;
  }

  /**
   * Whether the agent should run as current user or as server. If the agent is designed to only run
   * as the current web user, this property cannot be set to true.
   * 
   * @return runAsServer
   **/
  public Boolean getRunAsServer() {
    return runAsServer;
  }

  /**
   * Set runAsServer
   **/
  public void setRunAsServer(Boolean runAsServer) {
    this.runAsServer = runAsServer;
  }

  public AgentPayloadAsync runAsServer(Boolean runAsServer) {
    this.runAsServer = runAsServer;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentPayloadAsync {\n");

    sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    callbackUrlError: ").append(toIndentedString(callbackUrlError)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    runAsServer: ").append(toIndentedString(runAsServer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

