/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Light info on configured OAuth applications
 **/

public class AppInfo {

  @JsonbProperty("client_name")
  private String clientName;

  @JsonbProperty("client_uri")
  private String clientUri;

  @JsonbProperty("description")
  private String description;

  @JsonbProperty("logo_uri")
  private String logoUri;

  /**
   * Get clientName
   * 
   * @return clientName
   **/
  public String getClientName() {
    return clientName;
  }

  /**
   * Set clientName
   **/
  public void setClientName(String clientName) {
    this.clientName = clientName;
  }

  public AppInfo clientName(String clientName) {
    this.clientName = clientName;
    return this;
  }

  /**
   * Get clientUri
   * 
   * @return clientUri
   **/
  public String getClientUri() {
    return clientUri;
  }

  /**
   * Set clientUri
   **/
  public void setClientUri(String clientUri) {
    this.clientUri = clientUri;
  }

  public AppInfo clientUri(String clientUri) {
    this.clientUri = clientUri;
    return this;
  }

  /**
   * Get description
   * 
   * @return description
   **/
  public String getDescription() {
    return description;
  }

  /**
   * Set description
   **/
  public void setDescription(String description) {
    this.description = description;
  }

  public AppInfo description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get logoUri
   * 
   * @return logoUri
   **/
  public String getLogoUri() {
    return logoUri;
  }

  /**
   * Set logoUri
   **/
  public void setLogoUri(String logoUri) {
    this.logoUri = logoUri;
  }

  public AppInfo logoUri(String logoUri) {
    this.logoUri = logoUri;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppInfo {\n");

    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    clientUri: ").append(toIndentedString(clientUri)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    logoUri: ").append(toIndentedString(logoUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

