/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;
import jakarta.validation.constraints.NotNull;

/**
 * Basic database object. NOTE: This is fit for limited current purpose, not complete for production
 **/

public class DesignNSFSimple {

  /**
   * Datbase title
   **/
  @JsonbProperty("title")
  private String title;

  /**
   * programmatic filename of the template, like 'demo.ntf'
   **/
  @JsonbProperty("templateName")
  private String templateName;

  /**
   * Path in internet style relative to the Domino data directory
   **/
  @JsonbProperty("nsfPath")
  private String nsfPath;

  /**
   * Datbase title
   * 
   * @return title
   **/
  @NotNull
  public String getTitle() {
    return title;
  }

  /**
   * Set title
   **/
  public void setTitle(String title) {
    this.title = title;
  }

  public DesignNSFSimple title(String title) {
    this.title = title;
    return this;
  }

  /**
   * programmatic filename of the template, like &#39;demo.ntf&#39;
   * 
   * @return templateName
   **/
  public String getTemplateName() {
    return templateName;
  }

  /**
   * Set templateName
   **/
  public void setTemplateName(String templateName) {
    this.templateName = templateName;
  }

  public DesignNSFSimple templateName(String templateName) {
    this.templateName = templateName;
    return this;
  }

  /**
   * Path in internet style relative to the Domino data directory
   * 
   * @return nsfPath
   **/
  @NotNull
  public String getNsfPath() {
    return nsfPath;
  }

  /**
   * Set nsfPath
   **/
  public void setNsfPath(String nsfPath) {
    this.nsfPath = nsfPath;
  }

  public DesignNSFSimple nsfPath(String nsfPath) {
    this.nsfPath = nsfPath;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DesignNSFSimple {\n");

    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("    nsfPath: ").append(toIndentedString(nsfPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

