/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;
import jakarta.validation.constraints.NotNull;

/**
 * Definition design information for specific design element Form.
 **/

public class DesignFormSimple {

  /**
   * Indicates how to handle form replication conflicts.
   **/
  @JsonbProperty("@conflictaction")
  private String atConflictaction;

  @JsonbProperty("@hide")
  private String atHide;

  /**
   * The name of the form.
   **/
  @JsonbProperty("@name")
  private String atName;

  /**
   * The note ID of a document, which is uniquely identifies a document within a particular
   * database.
   **/
  @JsonbProperty("@noteid")
  private String atNoteid;

  /**
   * Universal Id of the document, uniquely identifies a document across all replicas of a database
   **/
  @JsonbProperty("@unid")
  private String atUnid;

  /**
   * Alternate names or alias of the form.
   **/
  @JsonbProperty("@alias")
  private String atAlias;

  /**
   * The fields on a forms.
   **/
  @JsonbProperty("fields")
  private List<DesignFieldSimple> fields = new ArrayList<>();

  public DesignFormSimple() {}

  @JsonbCreator
  public DesignFormSimple(
      @JsonbProperty(value = "@conflictaction", nillable = true) String atConflictaction,
      @JsonbProperty(value = "@hide", nillable = true) String atHide,
      @JsonbProperty(value = "@name", nillable = true) String atName,
      @JsonbProperty(value = "@noteid", nillable = true) String atNoteid,
      @JsonbProperty(value = "@unid", nillable = true) String atUnid,
      @JsonbProperty(value = "@alias", nillable = true) String atAlias) {
    this.atConflictaction = atConflictaction;
    this.atHide = atHide;
    this.atName = atName;
    this.atNoteid = atNoteid;
    this.atUnid = atUnid;
    this.atAlias = atAlias;
  }

  /**
   * Indicates how to handle form replication conflicts.
   * 
   * @return atConflictaction
   **/
  public String getAtConflictaction() {
    return atConflictaction;
  }


  /**
   * Get atHide
   * 
   * @return atHide
   **/
  public String getAtHide() {
    return atHide;
  }


  /**
   * The name of the form.
   * 
   * @return atName
   **/
  public String getAtName() {
    return atName;
  }


  /**
   * The note ID of a document, which is uniquely identifies a document within a particular
   * database.
   * 
   * @return atNoteid
   **/
  public String getAtNoteid() {
    return atNoteid;
  }


  /**
   * Universal Id of the document, uniquely identifies a document across all replicas of a database
   * 
   * @return atUnid
   **/
  public String getAtUnid() {
    return atUnid;
  }


  /**
   * Alternate names or alias of the form.
   * 
   * @return atAlias
   **/
  public String getAtAlias() {
    return atAlias;
  }


  /**
   * The fields on a forms.
   * 
   * @return fields
   **/
  @NotNull
  public List<DesignFieldSimple> getFields() {
    return fields;
  }

  /**
   * Set fields
   **/
  public void setFields(List<DesignFieldSimple> fields) {
    this.fields = fields;
  }

  public DesignFormSimple fields(List<DesignFieldSimple> fields) {
    this.fields = fields;
    return this;
  }

  public DesignFormSimple addFieldsItem(DesignFieldSimple fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DesignFormSimple {\n");

    sb.append("    atConflictaction: ").append(toIndentedString(atConflictaction)).append("\n");
    sb.append("    atHide: ").append(toIndentedString(atHide)).append("\n");
    sb.append("    atName: ").append(toIndentedString(atName)).append("\n");
    sb.append("    atNoteid: ").append(toIndentedString(atNoteid)).append("\n");
    sb.append("    atUnid: ").append(toIndentedString(atUnid)).append("\n");
    sb.append("    atAlias: ").append(toIndentedString(atAlias)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

