/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Detailed error message, might contain stacktrace
 **/

public class ErrorMessage {

  @JsonbProperty("details")
  private String details;

  @JsonbProperty("message")
  private String message;

  @JsonbProperty("status")
  private Integer status;

  /**
   * Get details
   * 
   * @return details
   **/
  public String getDetails() {
    return details;
  }

  /**
   * Set details
   **/
  public void setDetails(String details) {
    this.details = details;
  }

  public ErrorMessage details(String details) {
    this.details = details;
    return this;
  }

  /**
   * Get message
   * 
   * @return message
   **/
  public String getMessage() {
    return message;
  }

  /**
   * Set message
   **/
  public void setMessage(String message) {
    this.message = message;
  }

  public ErrorMessage message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get status
   * 
   * @return status
   **/
  public Integer getStatus() {
    return status;
  }

  /**
   * Set status
   **/
  public void setStatus(Integer status) {
    this.status = status;
  }

  public ErrorMessage status(Integer status) {
    this.status = status;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorMessage {\n");

    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

