/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import java.util.List;
import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Outcome of an operation
 **/

public class ExecutionResult {

  /**
   * Anything that went out with print(\"Hello World\") in the agent
   **/
  @JsonbProperty("console")
  private String console;

  /**
   * Array of execution results, should the agent write results
   **/
  @JsonbProperty("results")
  private List<ExecutionResultResultsInner> results = null;

  /**
   * Success or failure or error count
   **/
  @JsonbProperty("status")
  private String status;

  /**
   * Anything that went out with print(\&quot;Hello World\&quot;) in the agent
   * 
   * @return console
   **/
  public String getConsole() {
    return console;
  }

  /**
   * Set console
   **/
  public void setConsole(String console) {
    this.console = console;
  }

  public ExecutionResult console(String console) {
    this.console = console;
    return this;
  }

  /**
   * Array of execution results, should the agent write results
   * 
   * @return results
   **/
  public List<ExecutionResultResultsInner> getResults() {
    return results;
  }

  /**
   * Set results
   **/
  public void setResults(List<ExecutionResultResultsInner> results) {
    this.results = results;
  }

  public ExecutionResult results(List<ExecutionResultResultsInner> results) {
    this.results = results;
    return this;
  }

  public ExecutionResult addResultsItem(ExecutionResultResultsInner resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Success or failure or error count
   * 
   * @return status
   **/
  public String getStatus() {
    return status;
  }

  /**
   * Set status
   **/
  public void setStatus(String status) {
    this.status = status;
  }

  public ExecutionResult status(String status) {
    this.status = status;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionResult {\n");

    sb.append("    console: ").append(toIndentedString(console)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

