/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import java.time.OffsetDateTime;
import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Domino REST API specific details
 **/

public class KeepInfoDetails {

  @JsonbProperty("keep-name")
  private String keepName;

  @JsonbProperty("keep-desc")
  private String keepDesc;

  @JsonbProperty("keep-version")
  private String keepVersion;

  @JsonbProperty("keep-vendor")
  private String keepVendor;

  @JsonbProperty("image-build")
  private OffsetDateTime imageBuild;

  /**
   * Get keepName
   * 
   * @return keepName
   **/
  public String getKeepName() {
    return keepName;
  }

  /**
   * Set keepName
   **/
  public void setKeepName(String keepName) {
    this.keepName = keepName;
  }

  public KeepInfoDetails keepName(String keepName) {
    this.keepName = keepName;
    return this;
  }

  /**
   * Get keepDesc
   * 
   * @return keepDesc
   **/
  public String getKeepDesc() {
    return keepDesc;
  }

  /**
   * Set keepDesc
   **/
  public void setKeepDesc(String keepDesc) {
    this.keepDesc = keepDesc;
  }

  public KeepInfoDetails keepDesc(String keepDesc) {
    this.keepDesc = keepDesc;
    return this;
  }

  /**
   * Get keepVersion
   * 
   * @return keepVersion
   **/
  public String getKeepVersion() {
    return keepVersion;
  }

  /**
   * Set keepVersion
   **/
  public void setKeepVersion(String keepVersion) {
    this.keepVersion = keepVersion;
  }

  public KeepInfoDetails keepVersion(String keepVersion) {
    this.keepVersion = keepVersion;
    return this;
  }

  /**
   * Get keepVendor
   * 
   * @return keepVendor
   **/
  public String getKeepVendor() {
    return keepVendor;
  }

  /**
   * Set keepVendor
   **/
  public void setKeepVendor(String keepVendor) {
    this.keepVendor = keepVendor;
  }

  public KeepInfoDetails keepVendor(String keepVendor) {
    this.keepVendor = keepVendor;
    return this;
  }

  /**
   * Get imageBuild
   * 
   * @return imageBuild
   **/
  public OffsetDateTime getImageBuild() {
    return imageBuild;
  }

  /**
   * Set imageBuild
   **/
  public void setImageBuild(OffsetDateTime imageBuild) {
    this.imageBuild = imageBuild;
  }

  public KeepInfoDetails imageBuild(OffsetDateTime imageBuild) {
    this.imageBuild = imageBuild;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeepInfoDetails {\n");

    sb.append("    keepName: ").append(toIndentedString(keepName)).append("\n");
    sb.append("    keepDesc: ").append(toIndentedString(keepDesc)).append("\n");
    sb.append("    keepVersion: ").append(toIndentedString(keepVersion)).append("\n");
    sb.append("    keepVendor: ").append(toIndentedString(keepVendor)).append("\n");
    sb.append("    imageBuild: ").append(toIndentedString(imageBuild)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

