/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Domino part of Domino REST API info
 **/

public class KeepInfoDomino {

  @JsonbProperty("version")
  private String version;

  @JsonbProperty("buildNumber")
  private Integer buildNumber;

  @JsonbProperty("fixpackNumber")
  private Integer fixpackNumber;

  @JsonbProperty("hotfixNumber")
  private Integer hotfixNumber;

  @JsonbProperty("majorVersion")
  private Integer majorVersion;

  @JsonbProperty("minorVersion")
  private Integer minorVersion;

  @JsonbProperty("qmrNumber")
  private Integer qmrNumber;

  @JsonbProperty("qmuNumber")
  private Integer qmuNumber;

  @JsonbProperty("productionBuild")
  private Boolean productionBuild;

  /**
   * Get version
   * 
   * @return version
   **/
  public String getVersion() {
    return version;
  }

  /**
   * Set version
   **/
  public void setVersion(String version) {
    this.version = version;
  }

  public KeepInfoDomino version(String version) {
    this.version = version;
    return this;
  }

  /**
   * Get buildNumber
   * 
   * @return buildNumber
   **/
  public Integer getBuildNumber() {
    return buildNumber;
  }

  /**
   * Set buildNumber
   **/
  public void setBuildNumber(Integer buildNumber) {
    this.buildNumber = buildNumber;
  }

  public KeepInfoDomino buildNumber(Integer buildNumber) {
    this.buildNumber = buildNumber;
    return this;
  }

  /**
   * Get fixpackNumber
   * 
   * @return fixpackNumber
   **/
  public Integer getFixpackNumber() {
    return fixpackNumber;
  }

  /**
   * Set fixpackNumber
   **/
  public void setFixpackNumber(Integer fixpackNumber) {
    this.fixpackNumber = fixpackNumber;
  }

  public KeepInfoDomino fixpackNumber(Integer fixpackNumber) {
    this.fixpackNumber = fixpackNumber;
    return this;
  }

  /**
   * Get hotfixNumber
   * 
   * @return hotfixNumber
   **/
  public Integer getHotfixNumber() {
    return hotfixNumber;
  }

  /**
   * Set hotfixNumber
   **/
  public void setHotfixNumber(Integer hotfixNumber) {
    this.hotfixNumber = hotfixNumber;
  }

  public KeepInfoDomino hotfixNumber(Integer hotfixNumber) {
    this.hotfixNumber = hotfixNumber;
    return this;
  }

  /**
   * Get majorVersion
   * 
   * @return majorVersion
   **/
  public Integer getMajorVersion() {
    return majorVersion;
  }

  /**
   * Set majorVersion
   **/
  public void setMajorVersion(Integer majorVersion) {
    this.majorVersion = majorVersion;
  }

  public KeepInfoDomino majorVersion(Integer majorVersion) {
    this.majorVersion = majorVersion;
    return this;
  }

  /**
   * Get minorVersion
   * 
   * @return minorVersion
   **/
  public Integer getMinorVersion() {
    return minorVersion;
  }

  /**
   * Set minorVersion
   **/
  public void setMinorVersion(Integer minorVersion) {
    this.minorVersion = minorVersion;
  }

  public KeepInfoDomino minorVersion(Integer minorVersion) {
    this.minorVersion = minorVersion;
    return this;
  }

  /**
   * Get qmrNumber
   * 
   * @return qmrNumber
   **/
  public Integer getQmrNumber() {
    return qmrNumber;
  }

  /**
   * Set qmrNumber
   **/
  public void setQmrNumber(Integer qmrNumber) {
    this.qmrNumber = qmrNumber;
  }

  public KeepInfoDomino qmrNumber(Integer qmrNumber) {
    this.qmrNumber = qmrNumber;
    return this;
  }

  /**
   * Get qmuNumber
   * 
   * @return qmuNumber
   **/
  public Integer getQmuNumber() {
    return qmuNumber;
  }

  /**
   * Set qmuNumber
   **/
  public void setQmuNumber(Integer qmuNumber) {
    this.qmuNumber = qmuNumber;
  }

  public KeepInfoDomino qmuNumber(Integer qmuNumber) {
    this.qmuNumber = qmuNumber;
    return this;
  }

  /**
   * Get productionBuild
   * 
   * @return productionBuild
   **/
  public Boolean getProductionBuild() {
    return productionBuild;
  }

  /**
   * Set productionBuild
   **/
  public void setProductionBuild(Boolean productionBuild) {
    this.productionBuild = productionBuild;
  }

  public KeepInfoDomino productionBuild(Boolean productionBuild) {
    this.productionBuild = productionBuild;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeepInfoDomino {\n");

    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    buildNumber: ").append(toIndentedString(buildNumber)).append("\n");
    sb.append("    fixpackNumber: ").append(toIndentedString(fixpackNumber)).append("\n");
    sb.append("    hotfixNumber: ").append(toIndentedString(hotfixNumber)).append("\n");
    sb.append("    majorVersion: ").append(toIndentedString(majorVersion)).append("\n");
    sb.append("    minorVersion: ").append(toIndentedString(minorVersion)).append("\n");
    sb.append("    qmrNumber: ").append(toIndentedString(qmrNumber)).append("\n");
    sb.append("    qmuNumber: ").append(toIndentedString(qmuNumber)).append("\n");
    sb.append("    productionBuild: ").append(toIndentedString(productionBuild)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

