/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import java.util.List;
import jakarta.json.bind.annotation.JsonbProperty;
import jakarta.validation.constraints.NotNull;

/**
 * Query to be send to check if user can read/update/delete Domino REST API configurations
 **/

public class KeepAccessQuery {

  /**
   * List of file path to enquiry
   **/
  @JsonbProperty("databases")
  private List<String> databases = null;

  /**
   * Should the query check all databases on the current server - might take a while. Excludes mail
   * files
   **/
  @JsonbProperty("checkAllNsf")
  private Boolean checkAllNsf;

  /**
   * Should only databases with existing Domino REST API configurations be returned
   **/
  @JsonbProperty("onlyConfigured")
  private Boolean onlyConfigured;

  /**
   * List of file path to enquiry
   * 
   * @return databases
   **/
  public List<String> getDatabases() {
    return databases;
  }

  /**
   * Set databases
   **/
  public void setDatabases(List<String> databases) {
    this.databases = databases;
  }

  public KeepAccessQuery databases(List<String> databases) {
    this.databases = databases;
    return this;
  }

  public KeepAccessQuery addDatabasesItem(String databasesItem) {
    this.databases.add(databasesItem);
    return this;
  }

  /**
   * Should the query check all databases on the current server - might take a while. Excludes mail
   * files
   * 
   * @return checkAllNsf
   **/
  @NotNull
  public Boolean getCheckAllNsf() {
    return checkAllNsf;
  }

  /**
   * Set checkAllNsf
   **/
  public void setCheckAllNsf(Boolean checkAllNsf) {
    this.checkAllNsf = checkAllNsf;
  }

  public KeepAccessQuery checkAllNsf(Boolean checkAllNsf) {
    this.checkAllNsf = checkAllNsf;
    return this;
  }

  /**
   * Should only databases with existing Domino REST API configurations be returned
   * 
   * @return onlyConfigured
   **/
  @NotNull
  public Boolean getOnlyConfigured() {
    return onlyConfigured;
  }

  /**
   * Set onlyConfigured
   **/
  public void setOnlyConfigured(Boolean onlyConfigured) {
    this.onlyConfigured = onlyConfigured;
  }

  public KeepAccessQuery onlyConfigured(Boolean onlyConfigured) {
    this.onlyConfigured = onlyConfigured;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeepAccessQuery {\n");

    sb.append("    databases: ").append(toIndentedString(databases)).append("\n");
    sb.append("    checkAllNsf: ").append(toIndentedString(checkAllNsf)).append("\n");
    sb.append("    onlyConfigured: ").append(toIndentedString(onlyConfigured)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

