/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;
import jakarta.validation.constraints.NotNull;

/**
 * Response for a client_secret request. Client seccret is returned once
 **/

public class OAuthApplicationSecretResponse {

  /**
   * application ID, required as header for access
   **/
  @JsonbProperty("client_id")
  private String clientId;

  /**
   * The application secret generated by Domino REST API for the external application
   **/
  @JsonbProperty("client_secret")
  private String clientSecret;

  /**
   * application ID, required as header for access
   * 
   * @return clientId
   **/
  @NotNull
  public String getClientId() {
    return clientId;
  }

  /**
   * Set clientId
   **/
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public OAuthApplicationSecretResponse clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * The application secret generated by Domino REST API for the external application
   * 
   * @return clientSecret
   **/
  @NotNull
  public String getClientSecret() {
    return clientSecret;
  }

  /**
   * Set clientSecret
   **/
  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public OAuthApplicationSecretResponse clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthApplicationSecretResponse {\n");

    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

