/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import java.util.List;
import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Response for request of get OData service document of a database.
 **/

public class ODataDbResponse {

  /**
   * OData metadata URI of a database. OData metadata is a machine-readable description of the
   * entity model designed to enable client consumption
   **/
  @JsonbProperty("@odata.context")
  private String atOdataContext;

  /**
   * All OData service objects of a database.
   **/
  @JsonbProperty("value")
  private List<ODataServiceObject> value = null;

  /**
   * OData metadata URI of a database. OData metadata is a machine-readable description of the
   * entity model designed to enable client consumption
   * 
   * @return atOdataContext
   **/
  public String getAtOdataContext() {
    return atOdataContext;
  }

  /**
   * Set atOdataContext
   **/
  public void setAtOdataContext(String atOdataContext) {
    this.atOdataContext = atOdataContext;
  }

  public ODataDbResponse atOdataContext(String atOdataContext) {
    this.atOdataContext = atOdataContext;
    return this;
  }

  /**
   * All OData service objects of a database.
   * 
   * @return value
   **/
  public List<ODataServiceObject> getValue() {
    return value;
  }

  /**
   * Set value
   **/
  public void setValue(List<ODataServiceObject> value) {
    this.value = value;
  }

  public ODataDbResponse value(List<ODataServiceObject> value) {
    this.value = value;
    return this;
  }

  public ODataDbResponse addValueItem(ODataServiceObject valueItem) {
    this.value.add(valueItem);
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ODataDbResponse {\n");

    sb.append("    atOdataContext: ").append(toIndentedString(atOdataContext)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

