/**
 * Copyright © 2025 Jesse Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Definition for specified form or view of OData service document of a database.
 **/

public class ODataDocument {

  /**
   * The ID of the OData entity.
   **/
  @JsonbProperty("@odata.id")
  private String atOdataId;

  /**
   * The link used to edit/update the entity,
   **/
  @JsonbProperty("@odata.editLink")
  private String atOdataEditLink;

  /**
   * Weak ETag of the current document
   **/
  @JsonbProperty("@odata.etag")
  private String atOdataEtag;

  /**
   * Form name of a document
   **/
  @JsonbProperty("Form")
  private String form;

  /**
   * Primary key of a document, unique across NSF databases with matching replicaIds
   **/
  @JsonbProperty("Hex0040_unid")
  private String hex0040Unid;

  /**
   * The ID of the OData entity.
   * 
   * @return atOdataId
   **/
  public String getAtOdataId() {
    return atOdataId;
  }

  /**
   * Set atOdataId
   **/
  public void setAtOdataId(String atOdataId) {
    this.atOdataId = atOdataId;
  }

  public ODataDocument atOdataId(String atOdataId) {
    this.atOdataId = atOdataId;
    return this;
  }

  /**
   * The link used to edit/update the entity,
   * 
   * @return atOdataEditLink
   **/
  public String getAtOdataEditLink() {
    return atOdataEditLink;
  }

  /**
   * Set atOdataEditLink
   **/
  public void setAtOdataEditLink(String atOdataEditLink) {
    this.atOdataEditLink = atOdataEditLink;
  }

  public ODataDocument atOdataEditLink(String atOdataEditLink) {
    this.atOdataEditLink = atOdataEditLink;
    return this;
  }

  /**
   * Weak ETag of the current document
   * 
   * @return atOdataEtag
   **/
  public String getAtOdataEtag() {
    return atOdataEtag;
  }

  /**
   * Set atOdataEtag
   **/
  public void setAtOdataEtag(String atOdataEtag) {
    this.atOdataEtag = atOdataEtag;
  }

  public ODataDocument atOdataEtag(String atOdataEtag) {
    this.atOdataEtag = atOdataEtag;
    return this;
  }

  /**
   * Form name of a document
   * 
   * @return form
   **/
  public String getForm() {
    return form;
  }

  /**
   * Set form
   **/
  public void setForm(String form) {
    this.form = form;
  }

  public ODataDocument form(String form) {
    this.form = form;
    return this;
  }

  /**
   * Primary key of a document, unique across NSF databases with matching replicaIds
   * 
   * @return hex0040Unid
   **/
  public String getHex0040Unid() {
    return hex0040Unid;
  }

  /**
   * Set hex0040Unid
   **/
  public void setHex0040Unid(String hex0040Unid) {
    this.hex0040Unid = hex0040Unid;
  }

  public ODataDocument hex0040Unid(String hex0040Unid) {
    this.hex0040Unid = hex0040Unid;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ODataDocument {\n");

    sb.append("    atOdataId: ").append(toIndentedString(atOdataId)).append("\n");
    sb.append("    atOdataEditLink: ").append(toIndentedString(atOdataEditLink)).append("\n");
    sb.append("    atOdataEtag: ").append(toIndentedString(atOdataEtag)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    hex0040Unid: ").append(toIndentedString(hex0040Unid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

